### ISSUE TITLE
Unable to install dependencies (Step 1)

### ISSUE THREAD

**Issue by SmasherHell** [logstash-plugins/logstash-input-jdbc#32]
Hi,

Every time I try to execute `bundle install` in the source directory (checked out on tag v1.0.0) I get :

```
There was a NoMethodError while loading logstash-input-jdbc.gemspec: 
undefined method `metadata=' for #<Gem::Specification name=logstash-input-jdbc version=1.0.0> from
  /opt/logstash/plugin-source/logstash-input-jdbc/logstash-input-jdbc.gemspec:18:in `block in <main>' 
```

I work on Ubuntu 14.04 LTS, with logstash 1.5.3

**Comment by suyograo** [comment]
@SmasherHell whats your ruby version? `ruby -v`

**Comment by pafq** [comment]
@SmasherHell 

I have the same problem. 
You can't install Ruby using the apt-get, it will install a older version of ruby. You need to install ruby manually.
I install ruby 2.2.2p95 and that problem was solved.
